---
## re-use RHEL workshop code

- name: find ami for rhel
  ansible.builtin.include_tasks: ami_find_rhel.yml

- name: find ami for centos 6
  when: (centos6 is defined) and (centos6 is not none)
  ansible.builtin.include_tasks: ami_find_centos_6.yml

- name: find ami for centos 6 node

- name: save ami for centos 6 node

- name: find ami for centos 7
  when: (centos7 is defined) and (centos7 is not none)
  ansible.builtin.include_tasks: ami_find_centos_7.yml

- name: find ami for centos 7 node

- name: save ami for centos 7 node

- name: find ami for satellite
  register: sat_amis
  amazon.aws.ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info['satellite'].owners }}"
    filters:
      name: "{{ ec2_info['satellite'].filter }}"

- name: save ami for satellite
  ansible.builtin.set_fact:
    sat_ami: >
      {{ sat_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date')
      | last }}
