---
- name: Check User Privileges when auth_token is defined
  block:
    - ilo_manage:
        category: Systems
        command: CheckUserPrivileges
        baseuri: "{{ baseuri }}"
        auth_token: "{{ auth_token }}"
        required_permissions: "{{ required_permissions | default(['HostBIOSConfigPriv', 'HostNICConfigPriv', 'HostStorageConfigPriv']) }}"
      register: result

    - name: User Privileges Status
      debug:
        msg: "{{ result }}"

  when: auth_token is defined
