---
- name: Include tasks
  loop: "{{ operations }}"
  loop_control:
    loop_var: operation
  ansible.builtin.include_tasks: includes/{{ operation.name }}.yaml

- name: Validate input provided by user
  when:
    - (username is not defined or password is not defined) and (cert_file is not defined or key_file is not defined) and (auth_token is not defined)
  ansible.builtin.fail:
    msg: username/password or cert_file/key_file or auth_token is mandatory

- name: Fail when more than one valid authentication method is provided
  when:
    - ((username is defined or password is defined) and (cert_file is defined or key_file is defined) and auth_token is defined) or ((username is defined or password
      is defined) and (cert_file is defined or key_file is defined)) or ((username is defined or password is defined) and auth_token is defined) or ((cert_file is
      defined or key_file is defined) and auth_token is defined)
  ansible.builtin.fail:
    msg: Only one authentication method is allowed. Provide either username/password or cert_file/key_file or auth_token.
