---
- name: CentOS 7 instance size list length
  ansible.builtin.debug:
    msg: "CentOS 7 instance size list length: {{ ec2_info[centos7].size | length }}"

- name: Initialize/reset list count
  ansible.builtin.set_fact:
    list_count: "reset"

- name: Call CentOS 7 retry tasks include
  ansible.builtin.include_tasks: centos_7/centos_7_loop.yml
...
