
- name: Get service quota change history in region {{ customer_account_region }}
  ansible.builtin.command:
    cmd: '{{ service_code }}'
  register: quota_change_history
  changed_when: false

- name: Submit a new quota request in region {{ customer_account_region }} # noqa name[template]
  when: ((quota_change_history.stdout | from_json).RequestedQuotas | length == 0)
    or (((quota_change_history.stdout | from_json).RequestedQuotas[0].DesiredValue
    | int) != (item.value | int))
  ansible.builtin.command:
    cmd: '{{ service_code }}'
  changed_when: false
